nome = input('Digite seu nome completo: ')
print(f'Seu nome em letras maiúsculass é: {nome.upper()}')
print(f'Seu nome em letras minúsculas é: {nome.lower()}')
print(f'Seu nome tem ao todo {len(nome) - nome.count(" ")} letras')
print(f'Seu primeiro nome tem {len(nome.split()[0])} letras')